# Thin entrypoint — includes the generated agent launcher.
# Generated by vigilant-octo/agents/install.py because this repo had
# no root Makefile. Safe to extend with your own targets; the
# installer will not overwrite a Makefile once it exists.
include .agents/agents.mk
