# Multi-workflow agent launcher — workhorse quick start (generated).
#
# Generated by farrier (the prompt-library installer). Do not edit by hand;
# re-run `make agent-install` to regenerate. Include it from a root Makefile:
#
#   include .agents/agents.mk
#
# The agent runs in the workhorse Docker container against an installed workflow
# under .agents/workflows/<WF>. It uses your Claude subscription (seeded from
# ~/.claude/.credentials.json) and persists the agent's work, sessions, and run
# artifacts in named volumes.
#
# Local mode (default): the container clones THIS repo from a read-only bind
# mount (see .agents/local.compose.yaml) — no SSH key, token, or network needed,
# and the host working tree is never mutated. The clone uses your latest
# committed state on $(REPO_BRANCH).
#
# Installed workflows: research
#
# Native mode runs the published `workhorse-agent` package via pipx — no checkout
# required (only the Docker + SRC=1 targets need $(STABLEMATE_DIR)).
# Override WORKHORSE to pin a version or use a local source checkout, e.g.
#   make agent-native WORKHORSE="uv run --project /path/to/stablemate/workhorse workhorse"
#
# Usage:
#   make agent-run                 # Docker + local clone (default WF=research)
#   make agent-run WF=<name>       # pick another installed workflow
#   make agent-native              # native (no Docker, pipx) on THIS working tree (foreground)
#   make agent-native-bg           # native, detached — saves pid; watch with agent-logs
#   make agent-native SRC=1        # native from local source ($(LOCAL_WORKER)) — test engine changes pre-publish
#   make agent-logs                # follow the current run log (.agents/runs/<WF>.log)
#   make agent-stop                # stop a detached native run (agent-native-bg)
#   make agent-build               # rebuild image + run
#   make agent-hello               # smoke-test with hello-world
#   make agent-container-logs      # follow the Docker container logs
#   make agent-down                # stop containers (keep volumes)
#   make agent-reseed-auth         # clear auth + re-seed credentials
#   make agent-clean               # wipe ALL volumes
#   make agent-artifacts           # copy run artifacts into ./.agents/runs
#   make agent-install             # regenerate these adapters from the library
#   make agent-check               # verify adapters are up to date (no writes)

AGENTS_DIR     ?= $(abspath $(CURDIR)/../vigilant-octo/agents)
# Public stablemate checkout (workhorse runtime + farrier installer source).
# Needed only for Docker runs and SRC=1 local-source runs.
STABLEMATE_DIR ?= $(abspath $(CURDIR)/../stablemate)
LOCAL_WORKER   := $(STABLEMATE_DIR)/workhorse
# WF selects which installed workflow to run; defaults to the first installed.
WF           ?= research
WORKFLOW_DIR ?= $(CURDIR)/.agents/workflows/$(WF)
REPO_NAME    ?= vcmi-mapgen
REPO_BRANCH  ?= main
REPO_URL     ?= git@github.com:GabrielCpp/vcmi-mapgen.git
# Compose project name (default = first compose file's directory) → volume prefix.
PROJECT      ?= local-worker
# Native runs use the published PyPI package via pipx (no source checkout needed).
# Pin a version with WORKHORSE="pipx run --spec workhorse-agent==X.Y.Z workhorse".
#
# SRC=1 instead runs workhorse straight from the local source checkout
# ($(LOCAL_WORKER)) via uv — use it to exercise un-published engine changes in a
# real workflow before cutting a release. An explicit WORKHORSE=... overrides both.
# WORKHORSE_VERSION is the informational version printed at startup; it carries a
# "(...)" suffix naming which source is in effect.
ifeq ($(SRC),1)
WORKHORSE         ?= uv run --project $(LOCAL_WORKER) workhorse
WORKHORSE_VERSION ?= $(shell grep -m1 '^version' $(LOCAL_WORKER)/pyproject.toml 2>/dev/null | cut -d'"' -f2) (local source: $(LOCAL_WORKER))
endif
WORKHORSE         ?= pipx run --spec workhorse-agent workhorse
WORKHORSE_VERSION ?= $(shell pipx list --short 2>/dev/null | grep '^workhorse-agent ' | cut -d' ' -f2) (pipx install)

# farrier regenerates these adapters from the prompt library. Default uses the
# published PyPI package via pipx (no checkout needed); SRC=1 runs the local
# source under $(STABLEMATE_DIR)/farrier. The library CONTENT is located via the
# user's `farrier config set-library` home config; when a vigilant-octo checkout
# exists at $(AGENTS_DIR) we pass --library explicitly so no global config is
# required. First-time setup without a checkout:
#   pipx install farrier && farrier config set-library /path/to/vigilant-octo/agents
ifeq ($(SRC),1)
FARRIER ?= uv run --project $(STABLEMATE_DIR)/farrier farrier
endif
FARRIER ?= pipx run farrier
FARRIER_LIB_ARG := $(if $(wildcard $(AGENTS_DIR)/library),--library "$(AGENTS_DIR)",)

# Optional run knobs forwarded to workhorse (native targets):
#   RUN_ID      names the stable run dir (<workflow>-<RUN_ID>); default "default".
#   PARAMS      inline JSON of workflow params, e.g. '{"program":"hrnet-research"}'.
#   PARAMS_FILE path to a JSON file of workflow params (same effect as PARAMS).
AGENT_ARGS := $(if $(RUN_ID),--run-id "$(RUN_ID)") $(if $(PARAMS),--params '$(PARAMS)') $(if $(PARAMS_FILE),--params-file "$(PARAMS_FILE)")

# Layer the local-run override on top of the generic worker compose.
COMPOSE := docker compose \
	-f $(LOCAL_WORKER)/compose.yaml \
	-f $(CURDIR)/.agents/local.compose.yaml
ENVV := WORKFLOW_DIR="$(WORKFLOW_DIR)" REPO_SRC="$(CURDIR)" REPO_BRANCH="$(REPO_BRANCH)" REPO_NAME="$(REPO_NAME)"

# Per-workflow run log + pid (under the gitignored .agents/runs/).
RUNS_DIR     := $(CURDIR)/.agents/runs
LOG          := $(RUNS_DIR)/$(WF).log
PID          := $(RUNS_DIR)/$(WF).pid

.DEFAULT_GOAL := help

.PHONY: help agent-run agent-native agent-native-bg agent-build agent-hello agent-logs agent-container-logs agent-stop agent-down agent-clean agent-reseed-auth agent-artifacts agent-install agent-check

help: ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}'

agent-run: ## Run the selected workflow (Docker, local clone). Override with WF=<name>
	@mkdir -p $(RUNS_DIR)
	$(ENVV) $(COMPOSE) up --abort-on-container-exit 2>&1 | tee $(LOG)

agent-native: ## Run natively (no Docker, pipx) on THIS tree; logs tee'd to .agents/runs/$(WF).log
	@mkdir -p $(RUNS_DIR)
	@command -v claude >/dev/null || { echo "error: 'claude' CLI not on PATH"; exit 1; }
	@echo "using workhorse-agent $(WORKHORSE_VERSION)"
	PYTHONUNBUFFERED=1 AGENT_REPO_DIR="$(CURDIR)" $(WORKHORSE) \
		--workflow $(WORKFLOW_DIR)/workflow.yaml --runs-dir $(RUNS_DIR) $(AGENT_ARGS) 2>&1 | tee $(LOG)

agent-native-bg: ## Detached native run; saves pid to .agents/runs/$(WF).pid (watch: make agent-logs)
	@mkdir -p $(RUNS_DIR)
	@command -v claude >/dev/null || { echo "error: 'claude' CLI not on PATH"; exit 1; }
	@echo "using workhorse-agent $(WORKHORSE_VERSION)"
	@PYTHONUNBUFFERED=1 AGENT_REPO_DIR="$(CURDIR)" nohup $(WORKHORSE) \
		--workflow $(WORKFLOW_DIR)/workflow.yaml --runs-dir $(RUNS_DIR) $(AGENT_ARGS) >$(LOG) 2>&1 </dev/null & \
		echo $$! >$(PID); echo "started native run (pid $$(cat $(PID))) — follow: make agent-logs WF=$(WF) ; stop: make agent-stop WF=$(WF)"

agent-build: ## Rebuild the worker image, then run the workflow
	@mkdir -p $(RUNS_DIR)
	$(ENVV) $(COMPOSE) up --build --abort-on-container-exit 2>&1 | tee $(LOG)

agent-hello: ## Smoke-test the worker + auth with the hello-world workflow
	WORKFLOW_DIR="$(AGENTS_DIR)/workflows/hello-world" docker compose -f $(LOCAL_WORKER)/compose.yaml up --abort-on-container-exit

agent-logs: ## Follow the current run's log (.agents/runs/$(WF).log)
	@mkdir -p $(RUNS_DIR); touch $(LOG); tail -n +1 -F $(LOG)

agent-container-logs: ## Follow the Docker worker container's logs
	docker logs -f $(PROJECT)-agent-1

agent-stop: ## Stop a detached native run started with agent-native-bg
	@if [ -f $(PID) ] && kill -0 $$(cat $(PID)) 2>/dev/null; then \
		P=$$(cat $(PID)); pkill -TERM -P $$P 2>/dev/null || true; kill -TERM $$P 2>/dev/null || true; \
		echo "stopped native run (pid $$P)"; rm -f $(PID); \
	else echo "no running native run (pidfile absent or stale)"; rm -f $(PID) 2>/dev/null || true; fi

agent-down: ## Stop/remove worker containers (keeps volumes & agent work)
	$(ENVV) $(COMPOSE) down

agent-reseed-auth: agent-down ## Re-seed subscription creds from the host (clears sessions volume)
	-docker volume rm $(PROJECT)_claude-state

agent-clean: ## Remove ALL worker volumes — clone, sessions, AND run artifacts
	$(ENVV) $(COMPOSE) down -v

agent-artifacts: ## Copy run artifacts out of the runs volume into ./.agents/runs
	@mkdir -p $(CURDIR)/.agents/runs
	docker run --rm \
		-v $(PROJECT)_runs:/runs:ro \
		-v $(CURDIR)/.agents/runs:/out \
		alpine sh -c 'cp -a /runs/. /out/ 2>/dev/null || true; ls -la /out'

agent-install: ## Regenerate the agent adapters/skills/workflows from the prompt library
	$(FARRIER) --repo "$(CURDIR)" $(FARRIER_LIB_ARG)

agent-check: ## Verify generated agent adapters are up to date (no writes)
	@$(FARRIER) --repo "$(CURDIR)" --check $(FARRIER_LIB_ARG) \
		&& echo "✓ agent files are up to date" \
		|| { echo "↑ files above would be rewritten by 'make agent-install'"; exit 1; }
